In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.cluster import KMeans
amazon = pd.read_csv("https://raw.githubusercontent.com/pa1battula/PavanKumarbattula_IT533/main/Amazon_toy.csv", encoding="ISO-8859-1") #USE YOUR OWN GITHUB LINK HERE
amazon.dropna(inplace=True)

In [79]:
amazon = amazon.set_index('product_name')

In [81]:
amazon2 = amazon[['price','number_available_in_stock',	'number_of_reviews',	'number_of_answered_questions']]
amazon2.head()

price  \
product_name                                                
Dinosaur Eggs                                        0.29   
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)     0.38   
Latex Assorted Water Balloons, Pack of 40            0.39   
4 Packs of Mini Colouring Pencils (4 pencils in...   0.60   
100 Deep Red Rose Silk Petals Confetti - Weddin...   0.64   

                                                    number_available_in_stock  \
product_name                                                                    
Dinosaur Eggs                                                               3   
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)                            2   
Latex Assorted Water Balloons, Pack of 40                                   7   
4 Packs of Mini Colouring Pencils (4 pencils in...                          7   
100 Deep Red Rose Silk Petals Confetti - Weddin...                          6   

                                                    number_of_reviews  \
product_name                                                            
Dinosaur Eggs                                                       3   
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)                    2   
Latex Assorted Water Balloons, Pack of 40                           2   
4 Packs of Mini Colouring Pencils (4 pencils in...                 21   
100 Deep Red Rose Silk Petals Confetti - Weddin...                 10   

                                                    number_of_answered_questions  
product_name                                                                      
Dinosaur Eggs                                                                  2  
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)                               1  
Latex Assorted Water Balloons, Pack of 40                                      1  
4 Packs of Mini Colouring Pencils (4 pencils in...                             1  
100 Deep Red Rose Silk Petals Confetti - Weddin...                             2

In [82]:
# # Mean Normalization with StandardScaler

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
amazon2_array = sc.fit_transform(amazon2.values) #calculate μ & σ (fit) and apply the transformation(transform)
amazon2_array

array([[-0.43043632, -0.62884591, -0.20813825, -0.14346266],
       [-0.42849516, -0.73842478, -0.23363   , -0.21795561],
       [-0.42827947, -0.19053043, -0.23363   , -0.21795561],
       ...,
       [15.09154059, -0.73842478, -0.25912176, -0.21795561],
       [21.0263253 , -0.73842478, -0.18264649,  1.12291751],
       [52.18869012, -0.73842478, -0.25912176, -0.21795561]])

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
amazon2_array = sc.fit_transform(amazon2.values) #caluclate μ & σ (fit) and apply the transformation(transform)
amazon2_array

array([[-0.43043632, -0.62884591, -0.20813825, -0.14346266],
       [-0.42849516, -0.73842478, -0.23363   , -0.21795561],
       [-0.42827947, -0.19053043, -0.23363   , -0.21795561],
       ...,
       [15.09154059, -0.73842478, -0.25912176, -0.21795561],
       [21.0263253 , -0.73842478, -0.18264649,  1.12291751],
       [52.18869012, -0.73842478, -0.25912176, -0.21795561]])

In [84]:
# Assign the scaled data to a DataFrame & use the index and columns arguments to keep your original indices and column names:
amazon2_norm = pd.DataFrame(amazon2_array, index=amazon2.index, columns=amazon2.columns)
amazon2_norm

price  \
product_name                                                    
Dinosaur Eggs                                       -0.430436   
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)    -0.428495   
Latex Assorted Water Balloons, Pack of 40           -0.428279   
4 Packs of Mini Colouring Pencils (4 pencils in...  -0.423750   
100 Deep Red Rose Silk Petals Confetti - Weddin...  -0.422887   
...                                                       ...   
Parrot Bebop Drone 2 (White)                         9.052364   
Star Images E.T. Stunt Puppet Replica Action Fi...   9.225775   
Indiana Jones - 12 Inch Action Figures: Indiana...  15.091541   
DJI Phantom 2 with H3-3D Gimbal                     21.026325   
Bowen Designs - Marvel Statue Thor Classic Acti...  52.188690   

                                                    number_available_in_stock  \
product_name                                                                    
Dinosaur Eggs                                                       -0.628846   
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)                    -0.738425   
Latex Assorted Water Balloons, Pack of 40                           -0.190530   
4 Packs of Mini Colouring Pencils (4 pencils in...                  -0.190530   
100 Deep Red Rose Silk Petals Confetti - Weddin...                  -0.300109   
...                                                                       ...   
Parrot Bebop Drone 2 (White)                                         0.247785   
Star Images E.T. Stunt Puppet Replica Action Fi...                  -0.628846   
Indiana Jones - 12 Inch Action Figures: Indiana...                  -0.738425   
DJI Phantom 2 with H3-3D Gimbal                                     -0.738425   
Bowen Designs - Marvel Statue Thor Classic Acti...                  -0.738425   

                                                    number_of_reviews  \
product_name                                                            
Dinosaur Eggs                                               -0.208138   
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)            -0.233630   
Latex Assorted Water Balloons, Pack of 40                   -0.233630   
4 Packs of Mini Colouring Pencils (4 pencils in...           0.250713   
100 Deep Red Rose Silk Petals Confetti - Weddin...          -0.029696   
...                                                               ...   
Parrot Bebop Drone 2 (White)                                -0.055188   
Star Images E.T. Stunt Puppet Replica Action Fi...          -0.259122   
Indiana Jones - 12 Inch Action Figures: Indiana...          -0.259122   
DJI Phantom 2 with H3-3D Gimbal                             -0.182646   
Bowen Designs - Marvel Statue Thor Classic Acti...          -0.259122   

                                                    number_of_answered_questions  
product_name                                                                      
Dinosaur Eggs                                                          -0.143463  
Neopets 4 Trading Card Fun Packs (2 Bonus Cards)                       -0.217956  
Latex Assorted Water Balloons, Pack of 40                              -0.217956  
4 Packs of Mini Colouring Pencils (4 pencils in...                     -0.217956  
100 Deep Red Rose Silk Petals Confetti - Weddin...                     -0.143463  
...                                                                          ...  
Parrot Bebop Drone 2 (White)                                           -0.068970  
Star Images E.T. Stunt Puppet Replica Action Fi...                     -0.068970  
Indiana Jones - 12 Inch Action Figures: Indiana...                     -0.217956  
DJI Phantom 2 with H3-3D Gimbal                                         1.122918  
Bowen Designs - Marvel Statue Thor Classic Acti...                     -0.217956  

[6312 rows x 4 columns]

In [71]:
# On to clustering with kMeans. Note that the variable "labels" is an array which specifies which cluster each product belongs to:

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=6, ).fit(amazon3_norm)
labels = kmeans.labels_
labels

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 0, 0, ..., 5, 5, 4], dtype=int32)

In [72]:
groups = {0: [], 1: [], 2: [], 3: [], 4: [], 5: []} # We have 6 clusters
i = 0                                       # Initializing the row counter
for index, row in amazon3.iterrows():      # We are now going through each row in dog_data
    groups[labels[i]].append(index)         # and appending the cluster labels/ numbers to each index
    i += 1

## Now we make a pretty list:

for key, value in groups.items():           # the key is the cluster number and the value is the names of the dogs
    print ('CLUSTER %i' % key)
    for products in value:
        print("    %s" % products)
    print('\n')

Streaming output truncated to the last 5000 lines.
    21st BIRTHDAY GLITZ DESIGN BLACK & SILVER PARTY PACK BALLOON BANNER CANDLE BADGE
    Artists Collection Medium Paint By Numbers Night Watch
    BICYCLE Warrior Horse
    Triang USS Hue City CG66 Model
    Equivalent Fractions Snap Card Game
    Zvezda 1/72 Pz.Kpfw. IV Ausf.F2 # 6251 - Plastic Model Kit
    Creativity for Kids Butterfly Wind Chime Mini Kit
    Olympic Mascots 9cm Wenlock Union Jack Figurine
    2 Minutes Security Hourglass Sand Timer -Orange
    Boland Neon Flourescent Necklace Rave Fancy Dress Costume Outfit Party Accessory Add-on Popband Festival
    F104 Rubber Tires Front Type B (2)
    Tamiya 1/48 Zimmerit Coating Sheet for Tiger I Mid/Late # 12653
    HPi Z705 Set Screw M3 x 10mm [Grub Screws] New Genuine HPi Racing R/C Part!
    Poker Dice
    Santa Maxi Beard And Moustache Fake False Beards for fancy Dress Costumes Outfits Accessories Accessory
    Ultra Pro DECKBOX POK Pokemon C60 Card Game (Red and White)
